/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AxiosProvider: typeof import('../src/shared/providers/AxiosProvider/index')['default']
  const BlockContainer: typeof import('../src/shared/components/BlockContainer/index')['default']
  const ClockPanel: typeof import('../src/shared/components/ClockPanel/index')['default']
  const KB_SERVICE_API_PREFIX: typeof import('../src/shared/api/index')['KB_SERVICE_API_PREFIX']
  const QueryProvider: typeof import('../src/shared/providers/QueryProvider/index')['default']
  const ReactChart: typeof import('@bit-ocean/echarts')['ReactChart']
  const ScrollTable: typeof import('../src/shared/components/ScrollTable/index')['default']
  const TitleRow: typeof import('../src/shared/components/TitleRow/index')['default']
  const clsx: typeof import('clsx')['default']
  const createRef: typeof import('react')['createRef']
  const echarts: typeof import('../src/shared/echarts/index')['default']
  const forwardRef: typeof import('react')['forwardRef']
  const httpClient: typeof import('../src/shared/api/index')['httpClient']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const queryClient: typeof import('@/shared/query-client')['queryClient']
  const router: typeof import('@/shared/router')['router']
  const startTransition: typeof import('react')['startTransition']
  const useCallback: typeof import('react')['useCallback']
  const useChartStore: typeof import('../src/shared/store/chart')['useChartStore']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useId: typeof import('react')['useId']
  const useImmer: typeof import('use-immer')['useImmer']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useRouteStaticData: typeof import('../src/shared/hooks/useRouteStaticData')['useRouteStaticData']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
